### ISSUE TITLE
DocuSign documentation has broken links to example XML notification files

### ISSUE THREAD

**Issue by gh0st** [docusign/recipe-010-webhook-python#9]
In [this code example](https://developers.docusign.com/esign-rest-api/code-examples/webhook-status#source-files) there are links to example XML notification files under the [How it works](https://developers.docusign.com/esign-rest-api/code-examples/webhook-status#how-it-works) section.

>DocuSign calls your webhook with a notification XML file. Notification files contain the latest information about your envelope and its recipients. Example XML notification files: [envelope creation](https://www.docusign.com/supportdocs/api-docs-assets/DocuSign-REST-Recipes/010-webhook/example_sent_notification.xml?_ga=2.211351893.1135533333.1585152051-119814313.1583366216), [envelope completion](https://www.docusign.com/supportdocs/api-docs-assets/DocuSign-REST-Recipes/010-webhook/example_completed_notification.xml?_ga=2.215021783.1135533333.1585152051-119814313.1583366216).

The links are broken.

I'd love to see the example notification files. Either in XML or JSON (preferred).

**Comment by LarryKlugerDS** [comment]
Oops, sorry about that. I will work on it and update this ticket as I progress on it. Currently we only support XML notification files. JSON will be supported later this year. 

Also note that we now recommend that you use a PaaS system such as AWS to receive Connect webhook notifications. See https://www.docusign.com/blog/dsdev-webhook-listeners-part-4/ We also have code examples for this flow in multiple languages, see the connect- series of repos on github.com/docusign

**Comment by LarryKlugerDS** [comment]
I've uploaded some examples. Both have been pretty printed. See:

* [**webhook_eg_msg_sent.xml**](https://github.com/docusign/connect-node-listener-aws/blob/master/webhook_eg_msg_sent.xml) An example envelope sent XML message. 
* [**webhook_eg_msg_completed.xml**](https://github.com/docusign/connect-node-listener-aws/blob/master/webhook_eg_msg_completed.xml) An example envelope completed XML message. 

Note that this repo is obsolete. I will be removing it soon.
